[program:worker]
process_name=%(program_name)s_%(process_num)02d
command=php /srv/api/artisan queue:work redis --tries=2 --max-time=36000 --timeout=36000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=4
user=www-data
redirect_stderr=true
stdout_logfile = /var/log/worker/queue.log
loglevel=info
stopwaitsecs=36000
memory_limit=512M