[supervisord]
nodaemon=true
user=www-data
pidfile=/etc/supervisord.d/supervisord.pid
logfile=/var/log/worker/supervisord.log
logfile_maxbytes=1MB
[supervisorctl]
[inet_http_server]
port = 127.0.0.1:9001
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = supervisord.d/*.conf